# Python FastAPI Docker Compose Configuration

version: "3.8"

services:
  app:
    container_name: Drugs_API
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn main:app --host 0.0.0.0 --port 8001
    volumes:
      - .:/app
    ports:
        - "8001:8001"